import { defaultOperators, toFullOption } from "react-querybuilder";
import { musicalInstruments } from "./musical-instruments";

export const validator = (r) => !!r.value;

export const fields = [
  {
    name: "asin",
    label: "ASIN",
    placeholder: "Enter ASIN",
    validator,
  },
  {
    name: "parentAsin",
    label: "Parent ASIN",
    placeholder: "Enter Parent ASIN",
    //defaultOperator: "beginsWith",
    validator,
  },
  { name: "favorite", label: "Favorite", inputType: "number", validator },
  {
    name: "productId",
    label: "Product ID",
    placeholder: "Enter Product ID",
    //valueEditorType: "checkbox",
    //operators: defaultOperators.filter((op) => op.name === "="),
    //defaultValue: false,
    validator,
  },
  {
    name: "upc",
    label: "UPC",
    placeholder: "Enter UPC",
    // valueEditorType: "select",
    // values: musicalInstruments,
    // defaultValue: "Cowbell",
    // operators: defaultOperators.filter((op) => op.name === "="),
    validator,
  },
  {
    name: "ean",
    label: "EAN",
    placeholder: "Enter EAN",
    validator,
  },
  {
    name: "isbn",
    label: "ISBN",
    placeholder: "Enter ISBN",
    validator,
  },
  {
    name: "category",
    label: "Category",
    placeholder: "Enter Category",
    validator,
  },
  {
    name: "brand",
    label: "Brand",
    placeholder: "Enter Brand",
    validator,
  },
  {
    name: "buyerIndustry",
    label: "Buyer Industry",
    placeholder: "Enter Buyer Industry",
    validator,
  },
  {
    name: "pageViews",
    label: "Page Views",
    placeholder: "Enter Page Views",
    validator,
  },
  {
    name: "productPerformance",
    label: "Product Performance",
    placeholder: "Enter Product Performance",
    validator,
  },
  {
    name: "b2bSalesRank",
    label: "B2B Sales Rank",
    placeholder: "Enter B2B Sales Rank",
    validator,
  },
  {
    name: "subCategory",
    label: "Sub Category",
    placeholder: "Enter Sub Category",
    validator,
  },
  {
    name: "lowestPriceLastWeek",
    label: "Lowest Price Last Week",
    placeholder: "Enter Lowest Price Last Week",
    validator,
  },
  {
    name: "wasFbaOffer",
    label: "Was FBA Offer",
    validator,
  },
  {
    name: "brandYouOffer",
    label: "Brand You Offer",
    validator,
  },
  {
    name: "categoryYouOffer",
    label: "Category You Offer",
    validator,
  },
  {
    name: "productOnAmazon",
    label: "Product On Amazon",
    validator,
  },
  {
    name: "estSales",
    label: "Est Sales",
    placeholder: "Enter Est Sales",
    validator,
  },
  {
    name: "profit",
    label: "Profit",
    placeholder: "Enter Profit",
    validator,
  },
  {
    name: "margin",
    label: "Margin",
    placeholder: "Enter Margin",
    validator,
  },
  {
    name: "roi",
    label: "ROI",
    placeholder: "Enter ROI",
    validator,
  },
  {
    name: "isTopLabelCategory",
    label: "Is Top Label Category",
    validator,
  },
  {
    name: "category",
    label: "Category",
    placeholder: "Enter Category",
    validator,
  },
  {
    name: "salesRank",
    label: "Sales Rank",
    placeholder: "Enter Sales Rank",
    validator,
  },
  {
    name: "avgSalesRank30d",
    label: "Avg Sales Rank 30d",
    validator,
  },
  {
    name: "avgSalesRank90d",
    label: "Avg Sales Rank 90d",
    validator,
  },
  {
    name: "avgSalesRank180d",
    label: "Avg Sales Rank 180d",
    validator,
  },
  {
    name: "lowestSalesRank30d",
    label: "Lowest Sales Rank 30d",
    validator,
  },
  {
    name: "lowestSalesRank90d",
    label: "Lowest Sales Rank 90d",
    validator,
  },
  {
    name: "lowestSalesRank180d",
    label: "Lowest Sales Rank 180d",
    validator,
  },
  {
    name: "salesRankDrops30d",
    label: "Sales Rank Drops 30d",
    validator,
  },
  {
    name: "salesRankDrops90d",
    label: "Sales Rank Drops 90d",
    validator,
  },
  {
    name: "salesRankDrops180d",
    label: "Sales Rank Drops 180d",
    validator,
  },
  {
    name: "cost",
    label: "Cost",
    placeholder: "Enter Cost",
    validator,
  },
  {
    name: "sellPrice",
    label: "Sell Price",
    placeholder: "Enter Sell Price",
    validator,
  },
  {
    name: "lowestFbm",
    label: "Lowest FBM",
    placeholder: "Enter Lowest FBM",
    validator,
  },
  {
    name: "referralFee",
    label: "Referral Fee",
    placeholder: "Enter Referral Fee",
    validator,
  },
  {
    name: "variableClosingFee",
    label: "Variable Closing Fee",
    placeholder: "Enter Variable Closing Fee",
    validator,
  },
  {
    name: "fulfillmentSubtotal",
    label: "Fulfillment Subtotal",
    placeholder: "Enter Fulfillment Subtotal",
    validator,
  },
  {
    name: "costSubTotal",
    label: "Cost Sub Total",
    placeholder: "Enter Cost Sub Total",
    validator,
  },
  {
    name: "sellerProceeds",
    label: "Seller Proceeds",
    placeholder: "Enter Seller Proceeds",
    validator,
  },
  {
    name: "vatPerc",
    label: "VAT %",
    placeholder: "Enter VAT %",
    validator,
  },
  {
    name: "vatBuck",
    label: "VAT $",
    placeholder: "Enter VAT $",
    validator,
  },
  {
    name: "inboundShippingEstimate",
    label: "Inbounf Shipping Estimate",
    placeholder: "Enter Inbounf Shipping Estimate",
    validator,
  },
  {
    name: "packageDimensions",
    label: "Package Dimensions",
    placeholder: "Enter Package Dimensions",
    validator,
  },
  {
    name: "packageWeight",
    label: "Package Weight",
    placeholder: "Enter Package Weight",
    validator,
  },
  {
    name: "amazonSellerInStockRate30d",
    label: "Amazon Seller InStock Rate 30d",
    placeholder: "Enter Amazon Seller InStock Rate 30d",
    validator,
  },
  {
    name: "amazonSellerInStockRate90d",
    label: "Amazon Seller InStock Rate 90d",
    placeholder: "Enter Amazon Seller InStock Rate 90d",
    validator,
  },
  {
    name: "amazonSellerInStockRate180d",
    label: "Amazon Seller InStock Rate 180d",
    placeholder: "Enter Amazon Seller InStock Rate 180d",
    validator,
  },
  {
    name: "amazonSeller",
    label: "Amazon Seller",
    placeholder: "Enter Amazon Seller",
    validator,
  },
  {
    name: "reviews",
    label: "Reviews",
    placeholder: "Enter Reviews",
    validator,
  },
  {
    name: "Ratings",
    label: "Ratings",
    placeholder: "Enter Ratings",
    validator,
  },
  //   {
  //     name: "alsoPlays",
  //     label: "Also plays",
  //     valueEditorType: "multiselect",
  //     values: musicalInstruments,
  //     defaultValue: "More cowbell",
  //     operators: defaultOperators.filter((op) => op.name === "in"),
  //   },
  //   {
  //     name: "gender",
  //     label: "Gender",
  //     operators: defaultOperators.filter((op) => op.name === "="),
  //     valueEditorType: "radio",
  //     values: [
  //       { name: "M", label: "Male" },
  //       { name: "F", label: "Female" },
  //       { name: "O", label: "Other" },
  //     ],
  //   },
  //   { name: "height", label: "Height", validator },
  //   { name: "job", label: "Job", validator },
  //   { name: "description", label: "Description", valueEditorType: "textarea" },
  //   { name: "birthdate", label: "Birth Date", inputType: "date" },
  //   { name: "datetime", label: "Show Time", inputType: "datetime-local" },
  //   { name: "alarm", label: "Daily Alarm", inputType: "time" },
  //   {
  //     name: "groupedField1",
  //     label: "Grouped Field 1",
  //     comparator: "groupNumber",
  //     groupNumber: "group1",
  //     valueSources: ["field", "value"],
  //   },
  //   {
  //     name: "groupedField2",
  //     label: "Grouped Field 2",
  //     comparator: "groupNumber",
  //     groupNumber: "group1",
  //     valueSources: ["field", "value"],
  //   },
  //   {
  //     name: "groupedField3",
  //     label: "Grouped Field 3",
  //     comparator: "groupNumber",
  //     groupNumber: "group1",
  //     valueSources: ["field", "value"],
  //   },
  //   {
  //     name: "groupedField4",
  //     label: "Grouped Field 4",
  //     comparator: "groupNumber",
  //     groupNumber: "group1",
  //     valueSources: ["field", "value"],
  //   },
].map(toFullOption);
