import vendorKehe from "../assets/kehe-icon.png";

export const crmTableData = [
  {
    id: 1,
    vendorName: "Liandri Mining Corp.",
    userCategory: "Default",
    vendorStatus: "Prospect",
    amazonCategory: "N/A",
    paymentStatus: "Prepaid",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "liandri_co@gmail.com",
    totalPos: 16,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
  {
    id: 2,
    vendorName: "Izanagi Corp.",
    vendorImage: vendorKehe,
    userCategory: "Default",
    vendorStatus: "Open",
    amazonCategory: "N/A",
    paymentStatus: "Credit Card",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "izanagi@gmail.com",
    totalPos: 10,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
  {
    id: 3,
    vendorName: "Phayder Corp.",
    vendorImage: null,
    userCategory: "Default",
    vendorStatus: "Rejected",
    amazonCategory: "N/A",
    paymentStatus: "ACH",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "phayder_corp@gmail.com",
    totalPos: 10,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
  {
    id: 4,
    vendorName: "Axon Research Corp.",
    userCategory: "Default",
    vendorStatus: "Closed",
    amazonCategory: "N/A",
    paymentStatus: "Net 30 Terms",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "axon_group@gmail.com",
    totalPos: 10,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
  {
    id: 5,
    vendorName: "Izanagi Corp.",
    vendorImage: vendorKehe,
    userCategory: "Default",
    vendorStatus: "Rejected",
    amazonCategory: "N/A",
    paymentStatus: "Prepaid",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "izanagi@gmail.com",
    totalPos: 10,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
  {
    id: 6,
    vendorName: "Liandri Mining Corp.",
    userCategory: "Default",
    vendorStatus: "Prospect",
    amazonCategory: "N/A",
    paymentStatus: "Credit Card",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "liandri_co@gmail.com",
    totalPos: 10,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
  {
    id: 7,
    vendorName: "Izanagi Corp.",
    vendorImage: vendorKehe,
    userCategory: "Default",
    vendorStatus: "Rejected",
    amazonCategory: "N/A",
    paymentStatus: "Prepaid",
    leadTimeMin: "N/A",
    leadTimeMax: "N/A",
    phoneNumber: "188-500-1233",
    email: "izanagi@gmail.com",
    totalPos: 10,
    accountStatus: "Account open",
    vendorNote: "N/A",
    adress: {
      vendor: "Vendor Co",
      basedIn: "22 H, Zadmerg St, LA, 79001",
    },
  },
];
